language: python
python:
- '3.5.1'
install: pip install -r requirements.txt
script: nosetests
notifications:
  slack:
    secure: DLadOhg0Y5H0QmhgFcRf8uyzztdk7Y1rY/NAM4VX8KRdkgycXufWoPDCt0iv+3xPlAC/MqYCoHuPhL7mJ8UfX8jtRN2nnAg4UIxQ2hH76rxNrZttxqqT0Lx64/PuOOV0BPtxeil4qG1ecExU8FKR64Q4zWW6B5mw3zZj7m9G9oGawQSV9p1p/tvbhoqrxnZG9+qTFduxWOb/Hf+hZ1CoCPxUbjsm1wjEMuluHTE4pYWz4Wz5XpqB3efLTo/2A/CrRjVYIFoemz1ef32bvWL0L/Bmie2f/ZoQMKwHW8esHDEGYn363iASy4yLn1wcc4xsSZJpru98p2aznYvB9zeIAEgtFKBn8rNTRgUVJHpWxsz4s5rUbsfa3O/eP4d+rngV5jV5I80QX6bVAh5f4/DaLXgkLDTkqIvyzHOHr5t1AxBAQa1YesLkoOdwtLsqBl3hj+3+WYfg92tZbkK6Gid5SXXzylfOa4B0q+a2sGUjMsdzw/zxIPTUfjT20JG4E7c51ETdT0i1+/Q5JYRdtNB12AgNSTfPT7jRA7EdAa1QH8CYJdXQ2cj6WKvOkH3AZXxwWplwz0BzgJIZ+insGGFTaDDfEZ0vs2Xv94kmRuYQY8VMMf40BQ695DPgscHKmoOUh3P4ST31jJ4uf24/0GSSwEl1411YBcJfBWV1VVxAfRw=
